<?php

use App\Http\Controllers\Api\ActivityTermsController;
use App\Http\Controllers\Api\ActivityUseController;
use App\Http\Controllers\Api\AgentProgressController;
use App\Http\Controllers\Api\AiModelController;
use App\Http\Controllers\Api\AiProviderController;
use App\Http\Controllers\Api\ArchiveController;
use App\Http\Controllers\Api\AssistantController;
use App\Http\Controllers\Api\AssistantEmotionController;
use App\Http\Controllers\Api\AssistantImageController;
use App\Http\Controllers\Api\AssistantMemoryPromptController;
use App\Http\Controllers\Api\AssistantPoseAnimationController;
use App\Http\Controllers\Api\AssistantPoseController;
use App\Http\Controllers\Api\AssistantPromptController;
use App\Http\Controllers\Api\AssistantVrmController;
use App\Http\Controllers\Api\AssistantVrmLodController;
use App\Http\Controllers\Api\AvatarBackgroundController;
use App\Http\Controllers\Api\CampaignController;
use App\Http\Controllers\Api\ConversationBrowserController;
use App\Http\Controllers\Api\ConversationController;
use App\Http\Controllers\Api\ConversationMemoryController;
use App\Http\Controllers\Api\CreatorPasswordController;
use App\Http\Controllers\Api\DiscordController;
use App\Http\Controllers\Api\EmotionController;
use App\Http\Controllers\Api\FactController;
use App\Http\Controllers\Api\FactPlayController;
use App\Http\Controllers\Api\HandoverController;
use App\Http\Controllers\Api\ImageGenModelController;
use App\Http\Controllers\Api\ImageGenProviderController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\ItemController;
use App\Http\Controllers\Api\ItemImageController;
use App\Http\Controllers\Api\ItemSoundController;
use App\Http\Controllers\Api\ItemUseController;
use App\Http\Controllers\Api\NpcController;
use App\Http\Controllers\Api\PassageLinkController;
use App\Http\Controllers\Api\QuestController;
use App\Http\Controllers\Api\QuestOfferController;
use App\Http\Controllers\Api\QuestOptionsController;
use App\Http\Controllers\Api\QuestPlayController;
use App\Http\Controllers\Api\RegionController;
use App\Http\Controllers\Api\RegionImageController;
use App\Http\Controllers\Api\RegionTrackController;
use App\Http\Controllers\Api\ResidentActivityController;
use App\Http\Controllers\Api\ResidentConversationController;
use App\Http\Controllers\Api\ResidentDecisionController;
use App\Http\Controllers\Api\ResidentObservationController;
use App\Http\Controllers\Api\ResidentStateController;
use App\Http\Controllers\Api\SettingsController;
use App\Http\Controllers\Api\StartingInventoryController;
use App\Http\Controllers\Api\VoiceController;
use App\Http\Controllers\Api\VoiceModelController;
use App\Http\Controllers\Api\VoiceProviderController;
use App\Http\Controllers\Api\WorldController;
use App\Http\Controllers\Api\WorldImageController;
use App\Http\Controllers\Api\WorldResidentController;
use App\Http\Controllers\Api\WorldSessionController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user', fn (Request $request) => $request->user())->name('user.show');

    Route::get('/assistants', [AssistantController::class, 'index'])->name('assistants.index');
    Route::post('/assistants', [AssistantController::class, 'store'])->name('assistants.store');
    Route::get('/assistants/{id}', [AssistantController::class, 'show'])->name('assistants.show');
    Route::patch('/assistants/{id}', [AssistantController::class, 'update'])->name('assistants.update');
    Route::delete('/assistants/{id}', [AssistantController::class, 'destroy'])->name('assistants.destroy');
    Route::post('/assistants/{id}/vrm', [AssistantVrmController::class, 'store'])->name('assistants.vrm.store');
    Route::delete('/assistants/{id}/vrm', [AssistantVrmController::class, 'destroy'])->name('assistants.vrm.destroy');
    Route::post('/assistants/{id}/vrm/lod', [AssistantVrmLodController::class, 'store'])->name('assistants.vrm.lod.store');
    Route::delete('/assistants/{id}/vrm/lod', [AssistantVrmLodController::class, 'destroy'])->name('assistants.vrm.lod.destroy');
    Route::post('/assistants/{id}/image', [AssistantImageController::class, 'store'])->name('assistants.image.store');
    Route::delete('/assistants/{id}/image', [AssistantImageController::class, 'destroy'])->name('assistants.image.destroy');

    Route::apiResource('worlds', WorldController::class);
    Route::post('/worlds/{world}/card-image', [WorldImageController::class, 'storeCard'])->name('worlds.image.card.store');
    Route::delete('/worlds/{world}/card-image', [WorldImageController::class, 'destroyCard'])->name('worlds.image.card.destroy');
    Route::post('/worlds/{world}/portrait-image', [WorldImageController::class, 'storePortrait'])->name('worlds.image.portrait.store');
    Route::delete('/worlds/{world}/portrait-image', [WorldImageController::class, 'destroyPortrait'])->name('worlds.image.portrait.destroy');
    Route::scopeBindings()->group(function () {
        Route::post('/worlds/{world}/regions', [RegionController::class, 'store'])->name('worlds.regions.store');
        Route::get('/worlds/{world}/regions/{region}', [RegionController::class, 'show'])->name('worlds.regions.show');
        Route::patch('/worlds/{world}/regions/{region}', [RegionController::class, 'update'])->name('worlds.regions.update');
        Route::delete('/worlds/{world}/regions/{region}', [RegionController::class, 'destroy'])->name('worlds.regions.destroy');
        Route::post('/worlds/{world}/regions/{region}/card-image', [RegionImageController::class, 'storeCard'])->name('worlds.regions.image.card.store');
        Route::delete('/worlds/{world}/regions/{region}/card-image', [RegionImageController::class, 'destroyCard'])->name('worlds.regions.image.card.destroy');
        Route::post('/worlds/{world}/regions/{region}/portrait-image', [RegionImageController::class, 'storePortrait'])->name('worlds.regions.image.portrait.store');
        Route::delete('/worlds/{world}/regions/{region}/portrait-image', [RegionImageController::class, 'destroyPortrait'])->name('worlds.regions.image.portrait.destroy');
        Route::post('/worlds/{world}/regions/{region}/track', [RegionTrackController::class, 'store'])->name('worlds.regions.track.store');
        Route::delete('/worlds/{world}/regions/{region}/track', [RegionTrackController::class, 'destroy'])->name('worlds.regions.track.destroy');
        Route::put('/worlds/{world}/regions/{region}/passages/{passage}/link', [PassageLinkController::class, 'update'])->name('worlds.regions.passages.link.update');
        Route::delete('/worlds/{world}/regions/{region}/passages/{passage}/link', [PassageLinkController::class, 'destroy'])->name('worlds.regions.passages.link.destroy');
        Route::get('/worlds/{world}/items', [ItemController::class, 'index'])->name('worlds.items.index');
        Route::post('/worlds/{world}/items', [ItemController::class, 'store'])->name('worlds.items.store');
        Route::patch('/worlds/{world}/items/{item}', [ItemController::class, 'update'])->name('worlds.items.update');
        Route::delete('/worlds/{world}/items/{item}', [ItemController::class, 'destroy'])->name('worlds.items.destroy');
        Route::post('/worlds/{world}/items/{item}/card-image', [ItemImageController::class, 'storeCard'])->name('worlds.items.image.card.store');
        Route::post('/worlds/{world}/items/{item}/sound', [ItemSoundController::class, 'store'])->name('worlds.items.sound.store');
        Route::delete('/worlds/{world}/items/{item}/sound', [ItemSoundController::class, 'destroy'])->name('worlds.items.sound.destroy');
        Route::delete('/worlds/{world}/items/{item}/card-image', [ItemImageController::class, 'destroyCard'])->name('worlds.items.image.card.destroy');
        Route::get('/worlds/{world}/starting-inventories', [StartingInventoryController::class, 'index'])->name('worlds.starting-inventories.index');
        Route::put('/worlds/{world}/starting-inventories/player', [StartingInventoryController::class, 'updatePlayer'])->name('worlds.starting-inventories.player.update');
        Route::put('/worlds/{world}/starting-inventories/residents/{resident}', [StartingInventoryController::class, 'updateResident'])->name('worlds.starting-inventories.residents.update');
        Route::get('/worlds/{world}/facts', [FactController::class, 'world'])->name('worlds.facts.index');
        Route::get('/worlds/{world}/residents/{resident}/facts', [FactController::class, 'index'])->name('worlds.residents.facts.index');
        Route::post('/worlds/{world}/residents/{resident}/facts', [FactController::class, 'store'])->name('worlds.residents.facts.store');
        Route::patch('/worlds/{world}/residents/{resident}/facts/{fact}', [FactController::class, 'update'])->name('worlds.residents.facts.update');
        Route::delete('/worlds/{world}/residents/{resident}/facts/{fact}', [FactController::class, 'destroy'])->name('worlds.residents.facts.destroy');
        Route::get('/worlds/{world}/quests', [QuestController::class, 'index'])->name('worlds.quests.index');
        Route::post('/worlds/{world}/quests', [QuestController::class, 'store'])->name('worlds.quests.store');
        Route::patch('/worlds/{world}/quests/{quest}', [QuestController::class, 'update'])->name('worlds.quests.update');
        Route::delete('/worlds/{world}/quests/{quest}', [QuestController::class, 'destroy'])->name('worlds.quests.destroy');
        Route::get('/worlds/{world}/quest-options', QuestOptionsController::class)->name('worlds.quest-options');
        Route::get('/worlds/{world}/campaigns', [CampaignController::class, 'index'])->name('worlds.campaigns.index');
        Route::post('/worlds/{world}/campaigns', [CampaignController::class, 'store'])->name('worlds.campaigns.store');
        Route::patch('/worlds/{world}/campaigns/{campaign}', [CampaignController::class, 'update'])->name('worlds.campaigns.update');
        Route::delete('/worlds/{world}/campaigns/{campaign}', [CampaignController::class, 'destroy'])->name('worlds.campaigns.destroy');
        Route::get('/worlds/{world}/regions/{region}/activity-terms', [ActivityTermsController::class, 'index'])->name('worlds.regions.activity-terms.index');
        Route::put('/worlds/{world}/regions/{region}/objects/{object}/activities/{activity}/terms', [ActivityTermsController::class, 'update'])->name('worlds.regions.activity-terms.update');
        Route::delete('/worlds/{world}/regions/{region}/objects/{object}/activities/{activity}/terms', [ActivityTermsController::class, 'destroy'])->name('worlds.regions.activity-terms.destroy');
        Route::put('/worlds/{world}/regions/{region}/objects/{object}/starting-inventory', [StartingInventoryController::class, 'updateObject'])->name('worlds.regions.objects.starting-inventory.update');
    });
    Route::put('/worlds/{world}/regions/{region:id}/residents/{assistant}', [WorldResidentController::class, 'upsert'])->name('worlds.regions.residents.upsert');
    Route::delete('/worlds/{world}/regions/{region:id}/residents/{assistant}', [WorldResidentController::class, 'destroy'])->name('worlds.regions.residents.destroy');
    Route::post('/worlds/{world}/regions/{region:id}/residents/{assistant}/move', [WorldResidentController::class, 'move'])->name('worlds.regions.residents.move');
    Route::get('/worlds/{world}/sessions', [WorldSessionController::class, 'index'])->name('worlds.sessions.index');
    Route::post('/worlds/{world}/sessions', [WorldSessionController::class, 'store'])->name('worlds.sessions.store');
    Route::patch('/worlds/{world}/sessions/{session}', [WorldSessionController::class, 'update'])->name('worlds.sessions.update');
    Route::put('/worlds/{world}/sessions/{session}/position', [WorldSessionController::class, 'updatePosition'])->name('worlds.sessions.position.update');
    Route::delete('/worlds/{world}/sessions/{session}', [WorldSessionController::class, 'destroy'])->name('worlds.sessions.destroy');
    Route::post('/worlds/{world}/sessions/{session}/resume', [WorldSessionController::class, 'resume'])->name('worlds.sessions.resume');
    Route::post('/worlds/{world}/sessions/{session}/travel', [WorldSessionController::class, 'travel'])->name('worlds.sessions.travel');
    Route::post('/worlds/{world}/sessions/{session}/residents/{resident}/activities', [ResidentActivityController::class, 'store'])->name('worlds.sessions.residents.activities.store');
    Route::patch('/worlds/{world}/sessions/{session}/residents/{resident}/activities/{activity}', [ResidentActivityController::class, 'update'])->name('worlds.sessions.residents.activities.update');
    Route::put('/worlds/{world}/sessions/{session}/residents/{resident}/state', [ResidentStateController::class, 'update'])->name('worlds.sessions.residents.state.update');
    Route::post('/worlds/{world}/sessions/{session}/residents/{resident}/decisions', [ResidentDecisionController::class, 'store'])->name('worlds.sessions.residents.decisions.store');
    Route::post('/worlds/{world}/sessions/{session}/residents/{resident}/observations', [ResidentObservationController::class, 'store'])->name('worlds.sessions.residents.observations.store');
    Route::post('/worlds/{world}/sessions/{session}/residents/{resident}/conversations', [ResidentConversationController::class, 'store'])->name('worlds.sessions.residents.conversations.store');
    Route::get('/worlds/{world}/sessions/{session}/conversations/{conversation}', [ResidentConversationController::class, 'show'])->name('worlds.sessions.conversations.show');
    Route::post('/worlds/{world}/sessions/{session}/conversations/{conversation}/turns', [ResidentConversationController::class, 'turn'])->name('worlds.sessions.conversations.turns.store');
    Route::post('/worlds/{world}/sessions/{session}/conversations/{conversation}/pause', [ResidentConversationController::class, 'pause'])->name('worlds.sessions.conversations.pause');
    Route::post('/worlds/{world}/sessions/{session}/conversations/{conversation}/observers', [ResidentConversationController::class, 'observe'])->name('worlds.sessions.conversations.observers.store');
    Route::get('/worlds/{world}/sessions/{session}/inventory', [InventoryController::class, 'show'])->name('worlds.sessions.inventory.show');
    Route::post('/worlds/{world}/sessions/{session}/handovers', [HandoverController::class, 'store'])->name('worlds.sessions.handovers.store');
    Route::post('/worlds/{world}/sessions/{session}/handover-requests/{handoverRequest}/answer', [HandoverController::class, 'answer'])->name('worlds.sessions.handover-requests.answer');
    Route::post('/worlds/{world}/sessions/{session}/conversations/{conversation}/handover-requests/cancel', [HandoverController::class, 'cancel'])->name('worlds.sessions.conversations.handover-requests.cancel');
    Route::get('/worlds/{world}/sessions/{session}/residents/{resident}/goods', [InventoryController::class, 'goods'])->name('worlds.sessions.residents.goods.index');
    Route::get('/worlds/{world}/sessions/{session}/objects/{object}', [InventoryController::class, 'object'])->name('worlds.sessions.objects.show');
    Route::get('/worlds/{world}/sessions/{session}/known-facts', [FactPlayController::class, 'index'])->name('worlds.sessions.known-facts.index');
    Route::get('/worlds/{world}/sessions/{session}/quests', [QuestPlayController::class, 'index'])->name('worlds.sessions.quests.index');
    Route::get('/worlds/{world}/sessions/{session}/quest-events', [QuestPlayController::class, 'events'])->name('worlds.sessions.quest-events.index');
    Route::post('/worlds/{world}/sessions/{session}/quest-runs/{run}/abandon', [QuestPlayController::class, 'abandon'])->name('worlds.sessions.quest-runs.abandon');
    Route::post('/worlds/{world}/sessions/{session}/quest-offers/{offer}/answer', [QuestOfferController::class, 'answer'])->name('worlds.sessions.quest-offers.answer');
    Route::post('/worlds/{world}/sessions/{session}/conversations/{conversation}/quest-offers/withdraw', [QuestOfferController::class, 'withdraw'])->name('worlds.sessions.conversations.quest-offers.withdraw');
    Route::post('/worlds/{world}/sessions/{session}/quest-runs/{run}/assess', [QuestPlayController::class, 'assess'])->name('worlds.sessions.quest-runs.assess');
    Route::get('/worlds/{world}/sessions/{session}/reveal-attempts', [FactPlayController::class, 'revealAttempts'])->name('worlds.sessions.reveal-attempts.index');
    Route::get('/worlds/{world}/sessions/{session}/credit-history', [InventoryController::class, 'creditHistory'])->name('worlds.sessions.credit-history.index');
    Route::post('/worlds/{world}/sessions/{session}/activity-uses', [ActivityUseController::class, 'store'])->name('worlds.sessions.activity-uses.store');
    Route::get('/worlds/{world}/sessions/{session}/items/{item}/examine', [ItemUseController::class, 'examine'])->name('worlds.sessions.items.examine');
    Route::post('/worlds/{world}/sessions/{session}/items/{item}/use', [ItemUseController::class, 'use'])->name('worlds.sessions.items.use');
    Route::post('/worlds/{world}/sessions/{session}/objects/{object}/take', [InventoryController::class, 'take'])->name('worlds.sessions.objects.take');
    Route::get('/creator-password', [CreatorPasswordController::class, 'show'])->name('creator-password.show');
    Route::put('/creator-password', [CreatorPasswordController::class, 'update'])->name('creator-password.update');
    Route::get('/conversations', [ConversationBrowserController::class, 'index'])->name('conversation-browser.index');
    Route::get('/conversations/{conversation}', [ConversationBrowserController::class, 'show'])->name('conversation-browser.show');
    Route::apiResource('npcs', NpcController::class);

    Route::prefix('assistants/{assistant}')->group(function () {
        Route::get('/settings', [SettingsController::class, 'show'])->name('settings.show');
        Route::put('/settings', [SettingsController::class, 'update'])->name('settings.update');
        Route::put('/settings/model', [SettingsController::class, 'selectModel'])->name('settings.selectModel');
        Route::put('/settings/voice-model', [SettingsController::class, 'selectVoiceModel'])->name('settings.selectVoiceModel');
        Route::put('/settings/image-gen-model', [SettingsController::class, 'selectImageGenModel'])->name('settings.selectImageGenModel');
        Route::put('/settings/voice', [SettingsController::class, 'updateVoice'])->name('settings.updateVoice');
        Route::put('/settings/discord', [SettingsController::class, 'updateDiscord'])->name('settings.updateDiscord');
        Route::get('/discord/discovery', [DiscordController::class, 'discovery'])->name('discord.discovery');
        Route::put('/discord/servers/{guildId}/prompt', [DiscordController::class, 'updateServerPrompt'])->name('discord.servers.updatePrompt');
        Route::put('/discord/channels/{channelId}/prompt', [DiscordController::class, 'updateChannelPrompt'])->name('discord.channels.updatePrompt');
        Route::get('/conversations', [ConversationController::class, 'index'])->name('conversations.index');
        Route::post('/conversations', [ConversationController::class, 'store'])->name('conversations.store');
        Route::get('/conversations/{id}/messages', [ConversationController::class, 'show'])->name('conversations.show');
        Route::post('/conversations/{id}/messages', [ConversationController::class, 'sendMessage'])->name('conversations.sendMessage');
        Route::post('/discord-messages', [ConversationController::class, 'sendDiscordMessage'])->name('conversations.sendDiscordMessage');
        Route::delete('/conversations/{id}', [ConversationController::class, 'destroy'])->name('conversations.destroy');
        Route::patch('/conversations/{id}', [ConversationController::class, 'update'])->name('conversations.update');
        Route::get('/conversations/{id}/agent-progress', [AgentProgressController::class, 'show'])->name('conversations.agent-progress');
        Route::get('/conversations/{id}/avatar-background', [AvatarBackgroundController::class, 'show'])->name('conversations.avatar-background');
        Route::get('/conversations/{id}/memory', [ConversationMemoryController::class, 'show'])->name('memory.show');
        Route::put('/conversations/{id}/memory', [ConversationMemoryController::class, 'update'])->name('memory.update');
        Route::post('/conversations/{id}/memory/summarize', [ConversationMemoryController::class, 'summarize'])->name('memory.summarize');
        Route::post('/conversations/{id}/memory/unlock', [ConversationMemoryController::class, 'unlock'])->name('memory.unlock');
        Route::get('/prompt', [AssistantPromptController::class, 'show'])->name('prompt.show');
        Route::post('/prompt', [AssistantPromptController::class, 'store'])->name('prompt.store');
        Route::put('/prompt', [AssistantPromptController::class, 'update'])->name('prompt.update');
        Route::delete('/prompt', [AssistantPromptController::class, 'destroy'])->name('prompt.destroy');
        Route::get('/memory-prompt', [AssistantMemoryPromptController::class, 'show'])->name('memory-prompt.show');
        Route::put('/memory-prompt', [AssistantMemoryPromptController::class, 'update'])->name('memory-prompt.update');

        Route::post('/voice/transcribe', [VoiceController::class, 'transcribe'])->name('voice.transcribe');
        Route::post('/voice/synthesize', [VoiceController::class, 'synthesize'])->name('voice.synthesize');

        Route::get('/emotions', [EmotionController::class, 'index'])->name('emotions.index');
        Route::prefix('/emotions')->name('assistants.emotions.')->group(function () {
            Route::post('/', [AssistantEmotionController::class, 'store'])->name('store');
            Route::post('/{emotion}', [AssistantEmotionController::class, 'update'])->name('update');
            Route::delete('/{emotion}', [AssistantEmotionController::class, 'destroy'])->name('destroy');
        });

        Route::prefix('/poses')->name('assistants.poses.')->group(function () {
            // Registered before the {pose} wildcard routes below so the
            // literal "default" segment isn't swallowed by them.
            Route::post('/default', [AssistantPoseController::class, 'updateDefault'])->name('default.update');
            Route::post('/default/animation', [AssistantPoseAnimationController::class, 'storeDefault'])->name('default.animation.store');
            Route::delete('/default/animation', [AssistantPoseAnimationController::class, 'destroyDefault'])->name('default.animation.destroy');

            Route::post('/', [AssistantPoseController::class, 'store'])->name('store');
            Route::post('/{pose}', [AssistantPoseController::class, 'update'])->name('update');
            Route::delete('/{pose}', [AssistantPoseController::class, 'destroy'])->name('destroy');
            Route::post('/{pose}/animation', [AssistantPoseAnimationController::class, 'store'])->name('animation.store');
            Route::delete('/{pose}/animation', [AssistantPoseAnimationController::class, 'destroy'])->name('animation.destroy');
        });
    });

    Route::get('/ai-providers', [AiProviderController::class, 'index'])->name('ai-providers.index');
    Route::post('/ai-providers', [AiProviderController::class, 'store'])->name('ai-providers.store');
    Route::patch('/ai-providers/{id}', [AiProviderController::class, 'update'])->name('ai-providers.update');
    Route::delete('/ai-providers/{id}', [AiProviderController::class, 'destroy'])->name('ai-providers.destroy');

    Route::post('/ai-providers/{provider}/models', [AiModelController::class, 'store'])->name('ai-models.store');
    Route::patch('/ai-providers/{provider}/models/{model}', [AiModelController::class, 'update'])->name('ai-models.update');
    Route::delete('/ai-providers/{provider}/models/{model}', [AiModelController::class, 'destroy'])->name('ai-models.destroy');

    Route::get('/image-gen-providers', [ImageGenProviderController::class, 'index'])->name('image-gen-providers.index');
    Route::post('/image-gen-providers', [ImageGenProviderController::class, 'store'])->name('image-gen-providers.store');
    Route::patch('/image-gen-providers/{id}', [ImageGenProviderController::class, 'update'])->name('image-gen-providers.update');
    Route::delete('/image-gen-providers/{id}', [ImageGenProviderController::class, 'destroy'])->name('image-gen-providers.destroy');

    Route::post('/image-gen-providers/{provider}/models', [ImageGenModelController::class, 'store'])->name('image-gen-models.store');
    Route::patch('/image-gen-providers/{provider}/models/{model}', [ImageGenModelController::class, 'update'])->name('image-gen-models.update');
    Route::delete('/image-gen-providers/{provider}/models/{model}', [ImageGenModelController::class, 'destroy'])->name('image-gen-models.destroy');

    Route::get('/voice-providers', [VoiceProviderController::class, 'index'])->name('voice-providers.index');
    Route::post('/voice-providers', [VoiceProviderController::class, 'store'])->name('voice-providers.store');
    Route::put('/voice-providers/{id}', [VoiceProviderController::class, 'update'])->name('voice-providers.update');
    Route::patch('/voice-providers/{id}', [VoiceProviderController::class, 'updatePrompt'])->name('voice-providers.updatePrompt');
    Route::delete('/voice-providers/{id}', [VoiceProviderController::class, 'destroy'])->name('voice-providers.destroy');

    Route::post('/voice-providers/{provider}/models', [VoiceModelController::class, 'store'])->name('voice-models.store');
    Route::put('/voice-providers/{provider}/models/{model}', [VoiceModelController::class, 'update'])->name('voice-models.update');
    Route::patch('/voice-providers/{provider}/models/{model}', [VoiceModelController::class, 'updatePrompt'])->name('voice-models.updatePrompt');
    Route::delete('/voice-providers/{provider}/models/{model}', [VoiceModelController::class, 'destroy'])->name('voice-models.destroy');

    Route::get('/archives', [ArchiveController::class, 'index'])->name('archives.index');
    Route::get('/archives/{id}', [ArchiveController::class, 'show'])->name('archives.show');
    Route::get('/archives/{id}/export', [ArchiveController::class, 'export'])->name('archives.export');
    Route::get('/archives/{id}/search', [ArchiveController::class, 'search'])->name('archives.search');
    Route::post('/archives', [ArchiveController::class, 'save'])->name('archives.store');
    Route::post('/archives/{id}', [ArchiveController::class, 'save'])->name('archives.save');

});
