import { useEffect, useState } from 'react';
import { useNavigate, useOutletContext, useParams } from 'react-router-dom';
import { route } from 'ziggy-js';
import { api } from '../utils/api.js';
import Header from '../components/Header.jsx';
import WorldForm from '../components/WorldForm.jsx';
import WorldResidentsEditor from '../components/WorldResidentsEditor.jsx';
import WorldImagesEditor from '../components/WorldImagesEditor.jsx';
import WorldTrackEditor from '../components/WorldTrackEditor.jsx';
import ConfirmationModal from '../components/common/ConfirmationModal.jsx';

export default function EditWorldPage() {
	const { worldId } = useParams(); const navigate = useNavigate(); const { addToast } = useOutletContext();
	const [value, setValue] = useState(null); const [environment, setEnvironment] = useState(null); const [isSaving, setIsSaving] = useState(false); const [confirmingDelete, setConfirmingDelete] = useState(false);
	useEffect(() => { const load = async () => { const response = await api.get(route('worlds.show', { world: worldId })); if (!response.ok) return navigate('/worlds'); const world = await response.json(); setValue({ id: world.id, name: world.name, slug: world.slug, description: world.description, assistantContextPrompt: world.assistantContextPrompt, npcContextPrompt: world.npcContextPrompt, settings: world.settings ?? { theme: 'default' }, environmentUrl: world.environmentUrl, cardImageUrl: world.cardImageUrl, portraitImageUrl: world.portraitImageUrl, trackOriginalName: world.trackOriginalName, residents: world.residents ?? [] }); }; void load(); }, [navigate, worldId]);
	const save = async () => { setIsSaving(true); try { const form = new FormData(); form.append('name', value.name); form.append('slug', value.slug); form.append('description', value.description); form.append('assistantContextPrompt', value.assistantContextPrompt); form.append('npcContextPrompt', value.npcContextPrompt); form.append('settings', JSON.stringify(value.settings)); if (environment) form.append('environment', environment); const response = await api.patchForm(route('worlds.update', { world: worldId }), form); if (!response.ok) throw new Error((await response.json()).message); addToast('World saved', 'success'); } catch (error) { addToast(error.message || 'Failed to save world', 'error'); } finally { setIsSaving(false); } };
	const handleDelete = async () => { setConfirmingDelete(false); try { const response = await api.delete(route('worlds.destroy', { world: worldId })); if (!response.ok) throw new Error(); addToast('World deleted', 'success'); navigate('/worlds'); } catch { addToast('Failed to delete world', 'error'); } };
	if (!value) return null;
	return <><Header hideSettings onBack={() => navigate('/worlds')} actions={<button type="button" onClick={() => setConfirmingDelete(true)} className="text-danger text-[0.7rem] tracking-[0.1em] cursor-pointer hover:text-danger transition-colors">DELETE</button>}><span className="text-fg-2 text-lg tracking-[0.05em]">Edit World</span></Header><WorldForm value={value} onChange={setValue} environmentFile={environment} onEnvironmentChange={setEnvironment} isSaving={isSaving} submitLabel={save} imagesEditor={value.id && <WorldImagesEditor worldId={value.id} cardImageUrl={value.cardImageUrl} portraitImageUrl={value.portraitImageUrl} addToast={addToast} />} trackEditor={value.id && <WorldTrackEditor worldId={value.id} trackOriginalName={value.trackOriginalName} addToast={addToast} />}>{value.id && <WorldResidentsEditor world={value} onWorldChange={setValue} addToast={addToast} />}</WorldForm>{confirmingDelete && <ConfirmationModal title="Delete world" message={`Delete "${value.name}"? Its environment asset and resident placements will be removed. Assistants and NPCs will not be affected.`} options={[{ label: 'DELETE', value: 'confirm', destructive: true }, { label: 'CANCEL', value: 'cancel', cancel: true }]} onSelect={(selected) => { if (selected === 'confirm') handleDelete(); else setConfirmingDelete(false); }} />}</>;
}
